# 1. Packages

In [2]:
import pandas as pd
import numpy as np
import requests

# 2. Data Sourcing

## 2.1 Adult Literacy Rate

In [3]:
url = "https://ourworldindata.org/grapher/literacy-rate-adults.csv?v=1&csvType=full&useColumnShortNames=true"
storage_options = {'User-Agent': 'Mozilla/5.0'}
df_adultliteracy = pd.read_csv(url, storage_options=storage_options)

In [4]:
df_adultliteracy.head(100)

,entity,code,year,adult_literacy_rate__population_15plus_years__both_sexes__pct__lr_ag15t99
0,Afghanistan,AFG,1979,18.00000
1,Afghanistan,AFG,2011,31.00000
2,Afghanistan,AFG,2015,33.75384
3,Afghanistan,AFG,2021,37.00000
4,Albania,ALB,2001,99.00000
...,...,...,...,...
95,Botswana,BWA,2003,81.00000
96,Brazil,BRA,1980,75.00000
97,Brazil,BRA,2000,86.00000
98,Brazil,BRA,2004,89.00000
99,Brazil,BRA,2006,90.00000

## 2.2 Youth Literacy Rate

In [5]:
url = "https://ourworldindata.org/grapher/literacy-rate-of-young-men-and-women.csv?v=1&csvType=full&useColumnShortNames=true"
storage_options = {'User-Agent': 'Mozilla/5.0'}
df_youthliteracy = pd.read_csv(url, storage_options=storage_options)

In [6]:
df_youthliteracy

,entity,code,year,youth_literacy_rate__population_15_24_years__male__pct__lr_ag15t24_m,youth_literacy_rate__population_15_24_years__female__pct__lr_ag15t24_f,owid_region
0,Afghanistan,AFG,1979,46.00000,11.00000,Asia
1,Afghanistan,AFG,2011,62.00000,32.00000,Asia
2,Afghanistan,AFG,2015,57.73505,25.48416,Asia
3,Afghanistan,AFG,2021,71.00000,42.00000,Asia
4,Afghanistan,AFG,2022,83.40000,44.17171,Asia
...,...,...,...,...,...,...
1997,Zimbabwe,ZWE,1982,94.00000,85.00000,Africa
1998,Zimbabwe,ZWE,1992,97.00000,94.00000,Africa
1999,Zimbabwe,ZWE,2009,NaN,95.65000,Africa
2000,Zimbabwe,ZWE,2014,NaN,96.31000,Africa
2001,Zimbabwe,ZWE,2019,90.77383,94.21590,Africa

## 2.3 Illiterate Population

In [7]:
url = "https://ourworldindata.org/grapher/literate-and-illiterate-world-population.csv?v=1&csvType=full&useColumnShortNames=true"
storage_options = {'User-Agent': 'Mozilla/5.0'}
df_illiterate_pop = pd.read_csv(url, storage_options=storage_options)

In [8]:
df_illiterate_pop

           entity      code  year  illiteracy_rate  literacy_rate
0     Afghanistan       AFG  1950        97.000000        3.00000
1     Afghanistan       AFG  1979        82.000000       18.00000
2     Afghanistan       AFG  2011        69.000000       31.00000
3     Afghanistan       AFG  2015        66.246155       33.75384
4     Afghanistan       AFG  2021        63.000000       37.00000
...           ...       ...   ...              ...            ...
2054     Zanzibar  OWID_ZAN  1950        92.500000        7.50000
2055     Zimbabwe       ZWE  1950        77.500000       22.50000
2056     Zimbabwe       ZWE  1982        22.000000       78.00000
2057     Zimbabwe       ZWE  1992        16.000000       84.00000
2058     Zimbabwe       ZWE  2019         6.772453       93.22755

[2059 rows x 5 columns]

## 2.4 GDP per Capita

In [9]:
url = "https://ourworldindata.org/grapher/gdp-per-capita-worldbank.csv?v=1&csvType=full&useColumnShortNames=true"
storage_options = {'User-Agent': 'Mozilla/5.0'}
df_gdp_cap = pd.read_csv(url, storage_options=storage_options)

In [10]:
df_gdp_cap

           entity code  year  ny_gdp_pcap_pp_kd owid_region
0     Afghanistan  AFG  2000          1617.8264        Asia
1     Afghanistan  AFG  2001          1454.1108        Asia
2     Afghanistan  AFG  2002          1774.3087        Asia
3     Afghanistan  AFG  2003          1815.9282        Asia
4     Afghanistan  AFG  2004          1776.9182        Asia
...           ...  ...   ...                ...         ...
7235     Zimbabwe  ZWE  2020          4527.7197      Africa
7236     Zimbabwe  ZWE  2021          4827.0890      Africa
7237     Zimbabwe  ZWE  2022          5036.7610      Africa
7238     Zimbabwe  ZWE  2023          5218.0225      Africa
7239     Zimbabwe  ZWE  2024          5215.2530      Africa

[7240 rows x 5 columns]

## 2.5 Average Years of Schooling

In [11]:
url = "https://ourworldindata.org/grapher/literacy-rates-vs-average-years-of-schooling.csv?v=1&csvType=full&useColumnShortNames=true"
storage_options = {'User-Agent': 'Mozilla/5.0'}
df_schooling = pd.read_csv(url, storage_options=storage_options)

In [12]:
df_schooling

,entity,code,year,literacy_rate,mf_youth_and_adults__15_64_years__average_years_of_education,population_historical,owid_region
0,Afghanistan,AFG,1870,NaN,0.01,4101170.0,Asia
1,Afghanistan,AFG,1875,NaN,0.01,4193635.0,Asia
2,Afghanistan,AFG,1880,NaN,0.01,4288021.0,Asia
3,Afghanistan,AFG,1885,NaN,0.01,4384343.0,Asia
4,Afghanistan,AFG,1890,NaN,0.01,4482635.0,Asia
...,...,...,...,...,...,...,...
5360,Zimbabwe,ZWE,2005,NaN,7.65,12483433.0,Africa
5361,Zimbabwe,ZWE,2010,NaN,7.86,13356551.0,Africa
5362,Zimbabwe,ZWE,2015,NaN,8.03,14399008.0,Africa
5363,Zimbabwe,ZWE,2019,93.22755,NaN,15271377.0,Africa
5364,Zimbabwe,ZWE,2020,NaN,8.32,15526887.0,Africa

# 3. Data Understanding

In [13]:
df_literacy = pd.merge(df_adultliteracy, df_youthliteracy, on= ["entity", "year"], how= "outer")

In [14]:
df_literacy.head(5)

,entity,code_x,year,adult_literacy_rate__population_15plus_years__both_sexes__pct__lr_ag15t99,code_y,youth_literacy_rate__population_15_24_years__male__pct__lr_ag15t24_m,youth_literacy_rate__population_15_24_years__female__pct__lr_ag15t24_f,owid_region
0,Afghanistan,AFG,1979,18.00000,AFG,46.00000,11.00000,Asia
1,Afghanistan,AFG,2011,31.00000,AFG,62.00000,32.00000,Asia
2,Afghanistan,AFG,2015,33.75384,AFG,57.73505,25.48416,Asia
3,Afghanistan,AFG,2021,37.00000,AFG,71.00000,42.00000,Asia
4,Afghanistan,NaN,2022,NaN,AFG,83.40000,44.17171,Asia

In [15]:
df_literacy.to_csv("../data/df_literacy.csv", index = False)

In [16]:
df_gdp_schooling = pd.merge(df_gdp_cap, df_schooling, on= ["entity", "year"], how= "outer")

In [17]:
df_gdp_schooling

,entity,code_x,year,ny_gdp_pcap_pp_kd,owid_region_x,code_y,literacy_rate,mf_youth_and_adults__15_64_years__average_years_of_education,population_historical,owid_region_y
0,Afghanistan,NaN,1870,NaN,NaN,AFG,NaN,0.01,4101170.0,Asia
1,Afghanistan,NaN,1875,NaN,NaN,AFG,NaN,0.01,4193635.0,Asia
2,Afghanistan,NaN,1880,NaN,NaN,AFG,NaN,0.01,4288021.0,Asia
3,Afghanistan,NaN,1885,NaN,NaN,AFG,NaN,0.01,4384343.0,Asia
4,Afghanistan,NaN,1890,NaN,NaN,AFG,NaN,0.01,4482635.0,Asia
...,...,...,...,...,...,...,...,...,...,...
10828,Zimbabwe,ZWE,2020,4527.7197,Africa,ZWE,NaN,8.32,15526887.0,Africa
10829,Zimbabwe,ZWE,2021,4827.0890,Africa,NaN,NaN,NaN,NaN,NaN
10830,Zimbabwe,ZWE,2022,5036.7610,Africa,NaN,NaN,NaN,NaN,NaN
10831,Zimbabwe,ZWE,2023,5218.0225,Africa,NaN,NaN,NaN,NaN,NaN
10832,Zimbabwe,ZWE,2024,5215.2530,Africa,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_gdp_schooling.to_csv("../data/df_gdp_schooling.csv", index = False)

In [19]:
print(df_literacy.isnull().sum())

entity                                                                          0
code_x                                                                       1023
year                                                                            0
adult_literacy_rate__population_15plus_years__both_sexes__pct__lr_ag15t99     294
code_y                                                                        759
youth_literacy_rate__population_15_24_years__male__pct__lr_ag15t24_m           94
youth_literacy_rate__population_15_24_years__female__pct__lr_ag15t24_f         17
owid_region                                                                   808
dtype: int64

# 4. Data Cleaning

In [20]:
df_literacy.head(5)

,entity,code_x,year,adult_literacy_rate__population_15plus_years__both_sexes__pct__lr_ag15t99,code_y,youth_literacy_rate__population_15_24_years__male__pct__lr_ag15t24_m,youth_literacy_rate__population_15_24_years__female__pct__lr_ag15t24_f,owid_region
0,Afghanistan,AFG,1979,18.00000,AFG,46.00000,11.00000,Asia
1,Afghanistan,AFG,2011,31.00000,AFG,62.00000,32.00000,Asia
2,Afghanistan,AFG,2015,33.75384,AFG,57.73505,25.48416,Asia
3,Afghanistan,AFG,2021,37.00000,AFG,71.00000,42.00000,Asia
4,Afghanistan,NaN,2022,NaN,AFG,83.40000,44.17171,Asia

In [21]:
df_literacy = df_literacy.drop(columns=['code_x', 'code_y'])

In [34]:
df_literacy

,ENTITY,YEAR,ADULT_LITERACY,YOUTH_LITERACY_M,YOUTH_LITERACY_F,OWID_REGION
0,Afghanistan,1979,18.00000,46.00000,11.00000,Asia
1,Afghanistan,2011,31.00000,62.00000,32.00000,Asia
2,Afghanistan,2015,33.75384,57.73505,25.48416,Asia
3,Afghanistan,2021,37.00000,71.00000,42.00000,Asia
4,Afghanistan,2022,37.00000,83.40000,44.17171,Asia
...,...,...,...,...,...,...
2014,Zimbabwe,1982,78.00000,94.00000,85.00000,Africa
2015,Zimbabwe,1992,84.00000,97.00000,94.00000,Africa
2016,Zimbabwe,2009,84.00000,97.00000,95.65000,Africa
2017,Zimbabwe,2014,84.00000,97.00000,96.31000,Africa
2018,Zimbabwe,2019,93.22755,90.77383,94.21590,Africa

In [23]:
df_literacy.columns = ['ENTITY', 'YEAR', 'ADULT_LITERACY', 'YOUTH_LITERACY_M' ,'YOUTH_LITERACY_F', 'OWID_REGION']

In [24]:
df_literacy[['ADULT_LITERACY', 'YOUTH_LITERACY_M', 'YOUTH_LITERACY_F', 'OWID_REGION']]= df_literacy.groupby('ENTITY')[['ADULT_LITERACY', 'YOUTH_LITERACY_M', 'YOUTH_LITERACY_F', 'OWID_REGION']].ffill()

In [25]:
df_literacy[['ADULT_LITERACY', 'YOUTH_LITERACY_M', 'YOUTH_LITERACY_F', 'OWID_REGION']]= df_literacy.groupby('ENTITY')[['ADULT_LITERACY', 'YOUTH_LITERACY_M', 'YOUTH_LITERACY_F', 'OWID_REGION']].bfill()

In [26]:
df_literacy.loc[df_literacy['ENTITY'] == 'World', 'OWID_REGION'] = 'World'

In [27]:
df_literacy = df_literacy.dropna(subset=['OWID_REGION'])

In [28]:
df_literacy['ADULT_LITERACY'] = df_literacy.groupby('OWID_REGION')['ADULT_LITERACY'].transform(lambda x: x.fillna(x.mean()))

In [29]:
df_literacy['YOUTH_LITERACY_M'] = df_literacy.groupby('OWID_REGION')['YOUTH_LITERACY_M'].transform(lambda x: x.fillna(x.mean()))

In [30]:
df_literacy.isnull().sum()

ENTITY              0
YEAR                0
ADULT_LITERACY      0
YOUTH_LITERACY_M    0
YOUTH_LITERACY_F    0
OWID_REGION         0
dtype: int64

In [35]:
df_literacy.to_csv("../data/df_literacy.csv", index = False)

In [32]:
df_illiterate_pop

           entity      code  year  illiteracy_rate  literacy_rate
0     Afghanistan       AFG  1950        97.000000        3.00000
1     Afghanistan       AFG  1979        82.000000       18.00000
2     Afghanistan       AFG  2011        69.000000       31.00000
3     Afghanistan       AFG  2015        66.246155       33.75384
4     Afghanistan       AFG  2021        63.000000       37.00000
...           ...       ...   ...              ...            ...
2054     Zanzibar  OWID_ZAN  1950        92.500000        7.50000
2055     Zimbabwe       ZWE  1950        77.500000       22.50000
2056     Zimbabwe       ZWE  1982        22.000000       78.00000
2057     Zimbabwe       ZWE  1992        16.000000       84.00000
2058     Zimbabwe       ZWE  2019         6.772453       93.22755

[2059 rows x 5 columns]

In [37]:
df_illiterate_pop.dropna(subset=['code'], inplace=True)

In [38]:
df_illiterate_pop.to_csv("../data/df_illeteracy.csv", index = False)