### Packages Import

In [82]:
import pandas as pd
import requests
from datetime import datetime as dt

# Data Sourcing

## Adult Literacy Rate

In [83]:
url = "https://ourworldindata.org/grapher/literacy-rate-adults.csv?v=1&csvType=full&useColumnShortNames=true"
storage_options = {'User-Agent': 'Mozilla/5.0'}
df_alit = pd.read_csv(url, storage_options=storage_options)

In [84]:
df_alit.to_csv("../data/un_processed/adult_literacy_rate.csv", index = False)

In [85]:
df_alit.head()

,entity,code,year,adult_literacy_rate__population_15plus_years__both_sexes__pct__lr_ag15t99
0,Afghanistan,AFG,1979,18.00000
1,Afghanistan,AFG,2011,31.00000
2,Afghanistan,AFG,2015,33.75384
3,Afghanistan,AFG,2021,37.00000
4,Albania,ALB,2001,99.00000

In [86]:
df_alit.shape

(1725, 4)

In [87]:
df_alit.columns

Index(['entity', 'code', 'year',
       'adult_literacy_rate__population_15plus_years__both_sexes__pct__lr_ag15t99'],
      dtype='str')

In [88]:
df_alit.info()

<class 'pandas.DataFrame'>
RangeIndex: 1725 entries, 0 to 1724
Data columns (total 4 columns):
 #   Column                                                                     Non-Null Count  Dtype
---  ------                                                                     --------------  -----
 0   entity                                                                     1725 non-null   str
 1   code                                                                       996 non-null    str
 2   year                                                                       1725 non-null   int64
 3   adult_literacy_rate__population_15plus_years__both_sexes__pct__lr_ag15t99  1725 non-null   float64
dtypes: float64(1), int64(1), str(2)
memory usage: 54.0 KB

In [89]:
df_alit.describe()

,year,adult_literacy_rate__population_15plus_years__both_sexes__pct__lr_ag15t99
count,1725.000000,1725.000000
mean,2003.860870,77.336331
std,13.176796,19.335627
min,1970.000000,9.000000
25%,1994.000000,64.492390
50%,2007.000000,82.157580
75%,2015.000000,94.000000
max,2023.000000,100.000000

##  Youth Literacy Rate

In [90]:
url = "https://ourworldindata.org/grapher/literacy-rate-of-young-men-and-women.csv?v=1&csvType=full&useColumnShortNames=true"
storage_options = {'User-Agent': 'Mozilla/5.0'}
df_ylit = pd.read_csv(url, storage_options=storage_options)

In [91]:
df_ylit.to_csv("../data/un_processed/youth_literacy_rate.csv", index = False)

In [92]:
df_ylit.head()

,entity,code,year,youth_literacy_rate__population_15_24_years__male__pct__lr_ag15t24_m,youth_literacy_rate__population_15_24_years__female__pct__lr_ag15t24_f,owid_region
0,Afghanistan,AFG,1979,46.00000,11.00000,Asia
1,Afghanistan,AFG,2011,62.00000,32.00000,Asia
2,Afghanistan,AFG,2015,57.73505,25.48416,Asia
3,Afghanistan,AFG,2021,71.00000,42.00000,Asia
4,Afghanistan,AFG,2022,83.40000,44.17171,Asia

In [93]:
df_ylit.shape

(2002, 6)

In [94]:
df_ylit.columns

Index(['entity', 'code', 'year',
       'youth_literacy_rate__population_15_24_years__male__pct__lr_ag15t24_m',
       'youth_literacy_rate__population_15_24_years__female__pct__lr_ag15t24_f',
       'owid_region'],
      dtype='str')

In [95]:
df_ylit.info()

<class 'pandas.DataFrame'>
RangeIndex: 2002 entries, 0 to 2001
Data columns (total 6 columns):
 #   Column                                                                  Non-Null Count  Dtype
---  ------                                                                  --------------  -----
 0   entity                                                                  2002 non-null   str
 1   code                                                                    1260 non-null   str
 2   year                                                                    2002 non-null   int64
 3   youth_literacy_rate__population_15_24_years__male__pct__lr_ag15t24_m    1925 non-null   float64
 4   youth_literacy_rate__population_15_24_years__female__pct__lr_ag15t24_f  2002 non-null   float64
 5   owid_region                                                             1211 non-null   str
dtypes: float64(2), int64(1), str(3)
memory usage: 94.0 KB

In [96]:
df_ylit.describe()

,year,youth_literacy_rate__population_15_24_years__male__pct__lr_ag15t24_m,youth_literacy_rate__population_15_24_years__female__pct__lr_ag15t24_f
count,2002.000000,1925.000000,2002.000000
mean,2004.844156,89.394051,84.052252
std,12.765391,12.571677,19.450914
min,1970.000000,22.000000,7.000000
25%,1997.000000,84.000000,73.830225
50%,2007.000000,94.400000,93.590000
75%,2015.000000,98.600000,98.909690
max,2023.000000,100.000000,100.000000

## Illiterate Population

In [97]:
url = "https://ourworldindata.org/grapher/literate-and-illiterate-world-population.csv?v=1&csvType=full&useColumnShortNames=true"
storage_options = {'User-Agent': 'Mozilla/5.0'}
df_ip = pd.read_csv(url, storage_options=storage_options)

In [98]:
df_ip.to_csv("../data/un_processed/illiterate_population.csv", index = False)

In [99]:
df_ip.head()

        entity code  year  illiteracy_rate  literacy_rate
0  Afghanistan  AFG  1950        97.000000        3.00000
1  Afghanistan  AFG  1979        82.000000       18.00000
2  Afghanistan  AFG  2011        69.000000       31.00000
3  Afghanistan  AFG  2015        66.246155       33.75384
4  Afghanistan  AFG  2021        63.000000       37.00000

In [100]:
df_ip.shape

(2059, 5)

In [101]:
df_ip.columns

Index(['entity', 'code', 'year', 'illiteracy_rate', 'literacy_rate'], dtype='str')

In [102]:
df_ip.info()

<class 'pandas.DataFrame'>
RangeIndex: 2059 entries, 0 to 2058
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   entity           2059 non-null   str
 1   code             1326 non-null   str
 2   year             2059 non-null   int64
 3   illiteracy_rate  2059 non-null   float64
 4   literacy_rate    2059 non-null   float64
dtypes: float64(2), int64(1), str(2)
memory usage: 80.6 KB

In [103]:
df_ip.describe()

              year  illiteracy_rate  literacy_rate
count  2059.000000      2059.000000    2059.000000
mean   1986.084507        27.421922      72.578078
std      64.008447        24.485748      24.485748
min    1475.000000         0.000000       0.000000
25%    1983.000000         6.704529      57.981690
50%    2002.000000        21.000000      79.000000
75%    2013.000000        42.018310      93.295470
max    2023.000000       100.000000     100.000000

## GDP per Capita

In [104]:
url = "https://ourworldindata.org/grapher/gdp-per-capita-worldbank.csv?v=1&csvType=full&useColumnShortNames=true"
storage_options = {'User-Agent': 'Mozilla/5.0'}
df_gc = pd.read_csv(url, storage_options=storage_options)

In [105]:
df_gc.to_csv("../data/un_processed/GDP_per_capita.csv", index = False)

In [106]:
df_gc.head()

        entity code  year  ny_gdp_pcap_pp_kd owid_region
0  Afghanistan  AFG  2000          1617.8264        Asia
1  Afghanistan  AFG  2001          1454.1108        Asia
2  Afghanistan  AFG  2002          1774.3087        Asia
3  Afghanistan  AFG  2003          1815.9282        Asia
4  Afghanistan  AFG  2004          1776.9182        Asia

In [107]:
df_gc.shape

(7240, 5)

In [108]:
df_gc.columns

Index(['entity', 'code', 'year', 'ny_gdp_pcap_pp_kd', 'owid_region'], dtype='str')

In [109]:
df_gc.info()

<class 'pandas.DataFrame'>
RangeIndex: 7240 entries, 0 to 7239
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   entity             7240 non-null   str
 1   code               7240 non-null   str
 2   year               7240 non-null   int64
 3   ny_gdp_pcap_pp_kd  7240 non-null   float64
 4   owid_region        6785 non-null   str
dtypes: float64(1), int64(1), str(3)
memory usage: 282.9 KB

In [110]:
df_gc.describe()

              year  ny_gdp_pcap_pp_kd
count  7240.000000        7240.000000
mean   2007.196133       21842.835811
std      10.055073       23830.954113
min    1990.000000         510.822800
25%    1999.000000        4520.726250
50%    2007.000000       12714.597000
75%    2016.000000       32586.047750
max    2024.000000      174569.520000

## Average Years of Schooling

In [111]:
url = "https://ourworldindata.org/grapher/literacy-rates-vs-average-years-of-schooling.csv?v=1&csvType=full&useColumnShortNames=true"
storage_options = {'User-Agent': 'Mozilla/5.0'}
df_sc = pd.read_csv(url, storage_options=storage_options)

In [112]:
df_sc.to_csv("../data/un_processed/years_of_schooling.csv", index = False)

In [113]:
df_sc.head()

,entity,code,year,literacy_rate,mf_youth_and_adults__15_64_years__average_years_of_education,population_historical,owid_region
0,Afghanistan,AFG,1870,NaN,0.01,4101170.0,Asia
1,Afghanistan,AFG,1875,NaN,0.01,4193635.0,Asia
2,Afghanistan,AFG,1880,NaN,0.01,4288021.0,Asia
3,Afghanistan,AFG,1885,NaN,0.01,4384343.0,Asia
4,Afghanistan,AFG,1890,NaN,0.01,4482635.0,Asia

In [114]:
df_sc.shape

(5365, 7)

In [115]:
df_sc.columns

Index(['entity', 'code', 'year', 'literacy_rate',
       'mf_youth_and_adults__15_64_years__average_years_of_education',
       'population_historical', 'owid_region'],
      dtype='str')

In [116]:
df_sc.info()

<class 'pandas.DataFrame'>
RangeIndex: 5365 entries, 0 to 5364
Data columns (total 7 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   entity                                                        5365 non-null   str
 1   code                                                          4475 non-null   str
 2   year                                                          5365 non-null   int64
 3   literacy_rate                                                 2000 non-null   float64
 4   mf_youth_and_adults__15_64_years__average_years_of_education  3668 non-null   float64
 5   population_historical                                         4760 non-null   float64
 6   owid_region                                                   4472 non-null   str
dtypes: float64(3), int64(1), str(3)
memory usage: 293.5 KB

In [117]:
df_sc.describe()

,year,literacy_rate,mf_youth_and_adults__15_64_years__average_years_of_education,population_historical
count,5365.000000,2000.000000,3668.000000,4.760000e+03
mean,1959.712395,72.681799,3.815776,9.752739e+07
std,57.132278,24.567877,3.647976,3.848177e+08
min,1475.000000,0.000000,0.000000,1.612000e+03
25%,1920.000000,57.806607,0.530000,2.018601e+06
50%,1975.000000,79.138070,2.760000,6.498918e+06
75%,2005.000000,93.899618,6.370000,2.487424e+07
max,2023.000000,100.000000,13.740000,4.686811e+09

# Data Quality Assessment

## Adult Literacy Rate

In [118]:
df_alit.head()

,entity,code,year,adult_literacy_rate__population_15plus_years__both_sexes__pct__lr_ag15t99
0,Afghanistan,AFG,1979,18.00000
1,Afghanistan,AFG,2011,31.00000
2,Afghanistan,AFG,2015,33.75384
3,Afghanistan,AFG,2021,37.00000
4,Albania,ALB,2001,99.00000

In [119]:
df_alit[["adult_literacy_rate__population_15plus_years__both_sexes__pct__lr_ag15t99"]] = df_alit[["adult_literacy_rate__population_15plus_years__both_sexes__pct__lr_ag15t99"]].round(2)

In [120]:
df_alit.isnull().sum()

entity                                                                         0
code                                                                         729
year                                                                           0
adult_literacy_rate__population_15plus_years__both_sexes__pct__lr_ag15t99      0
dtype: int64

In [121]:
len(df_alit)

1725

In [122]:
# Percent of missing values
(df_alit.isnull().sum() / len(df_alit)) * 100

entity                                                                        0.00000
code                                                                         42.26087
year                                                                          0.00000
adult_literacy_rate__population_15plus_years__both_sexes__pct__lr_ag15t99     0.00000
dtype: float64

In [123]:
df_alit.duplicated().sum()

np.int64(0)

In [124]:
df_alit[df_alit.duplicated()]

Empty DataFrame
Columns: [entity, code, year, adult_literacy_rate__population_15plus_years__both_sexes__pct__lr_ag15t99]
Index: []

In [125]:
col = 'adult_literacy_rate__population_15plus_years__both_sexes__pct__lr_ag15t99'
((df_alit[col] < 0) | (df_alit[col] > 100)).sum()

np.int64(0)

In [126]:
now = dt.now()
(df_alit['year'] > now.year).sum()

np.int64(0)

**Assessment:** There are some missing values in the column **code**, **Columns** must be renamed and the groups, The **entity** columns has some grouped countries which needs to be removed

## Youth Literacy Rate

In [127]:
df_ylit.head()

,entity,code,year,youth_literacy_rate__population_15_24_years__male__pct__lr_ag15t24_m,youth_literacy_rate__population_15_24_years__female__pct__lr_ag15t24_f,owid_region
0,Afghanistan,AFG,1979,46.00000,11.00000,Asia
1,Afghanistan,AFG,2011,62.00000,32.00000,Asia
2,Afghanistan,AFG,2015,57.73505,25.48416,Asia
3,Afghanistan,AFG,2021,71.00000,42.00000,Asia
4,Afghanistan,AFG,2022,83.40000,44.17171,Asia

In [128]:
col1 = 'youth_literacy_rate__population_15_24_years__male__pct__lr_ag15t24_m'
col2 = 'youth_literacy_rate__population_15_24_years__female__pct__lr_ag15t24_f'
df_ylit[[col1, col2]] = df_ylit[[col1, col2]].round(2)

In [129]:
df_ylit.isnull().sum()

entity                                                                      0
code                                                                      742
year                                                                        0
youth_literacy_rate__population_15_24_years__male__pct__lr_ag15t24_m       77
youth_literacy_rate__population_15_24_years__female__pct__lr_ag15t24_f      0
owid_region                                                               791
dtype: int64

In [130]:
len(df_ylit)

2002

In [131]:
# Percent of missing values
(df_ylit.isnull().sum() / len(df_ylit)) * 100

entity                                                                     0.000000
code                                                                      37.062937
year                                                                       0.000000
youth_literacy_rate__population_15_24_years__male__pct__lr_ag15t24_m       3.846154
youth_literacy_rate__population_15_24_years__female__pct__lr_ag15t24_f     0.000000
owid_region                                                               39.510490
dtype: float64

In [132]:
df_ylit.duplicated().sum()

np.int64(0)

In [133]:
df_ylit[df_ylit.duplicated()]

Empty DataFrame
Columns: [entity, code, year, youth_literacy_rate__population_15_24_years__male__pct__lr_ag15t24_m, youth_literacy_rate__population_15_24_years__female__pct__lr_ag15t24_f, owid_region]
Index: []

In [134]:
print(((df_ylit[col1] < 0) | (df_ylit[col1] > 100)).sum())
print(((df_ylit[col2] < 0) | (df_ylit[col2] > 100)).sum())

0
0

In [135]:
(df_alit['year'] > now.year).sum()

np.int64(0)

**Assessment:** There are some missing values in the column **code**, **Columns** must be renamed and the groups, The **entity** columns has some grouped countries which needs to be removed

## Illiterate Population

In [136]:
df_ip.head()

        entity code  year  illiteracy_rate  literacy_rate
0  Afghanistan  AFG  1950        97.000000        3.00000
1  Afghanistan  AFG  1979        82.000000       18.00000
2  Afghanistan  AFG  2011        69.000000       31.00000
3  Afghanistan  AFG  2015        66.246155       33.75384
4  Afghanistan  AFG  2021        63.000000       37.00000

In [137]:
col1 = 'illiteracy_rate'
col2 = 'literacy_rate'
df_ip[[col1, col2]] = df_ip[[col1, col2]].round(2)

In [138]:
df_ip.isnull().sum()

entity               0
code               733
year                 0
illiteracy_rate      0
literacy_rate        0
dtype: int64

In [139]:
len(df_ip)

2059

In [140]:
# Percent of missing values
(df_ip.isnull().sum() / len(df_ip)) * 100

entity              0.000000
code               35.599806
year                0.000000
illiteracy_rate     0.000000
literacy_rate       0.000000
dtype: float64

In [141]:
df_ip.duplicated().sum()

np.int64(0)

In [142]:
df_ip[df_ip.duplicated()]

Empty DataFrame
Columns: [entity, code, year, illiteracy_rate, literacy_rate]
Index: []

In [143]:
col1 = 'illiteracy_rate'
col2 = 'literacy_rate'
print(((df_ip[col1] < 0) | (df_ip[col1] > 100)).sum())
print(((df_ip[col2] < 0) | (df_ip[col2] > 100)).sum())

0
0

In [144]:
df_ip[df_ip[col1] + df_ip[col2] > 100]

Empty DataFrame
Columns: [entity, code, year, illiteracy_rate, literacy_rate]
Index: []

In [145]:
(df_ip['year'] > now.year).sum()

np.int64(0)

**Assessment:** There are some missing values in the column **code**, **Columns** must be renamed and the groups, The **entity** columns has some grouped countries which needs to be removed

## GDP per Capita

In [146]:
df_gc.head()

        entity code  year  ny_gdp_pcap_pp_kd owid_region
0  Afghanistan  AFG  2000          1617.8264        Asia
1  Afghanistan  AFG  2001          1454.1108        Asia
2  Afghanistan  AFG  2002          1774.3087        Asia
3  Afghanistan  AFG  2003          1815.9282        Asia
4  Afghanistan  AFG  2004          1776.9182        Asia

In [147]:
df_gc.isnull().sum()

entity                 0
code                   0
year                   0
ny_gdp_pcap_pp_kd      0
owid_region          455
dtype: int64

In [148]:
len(df_gc)

7240

In [149]:
# Percent of missing values
(df_gc.isnull().sum() / len(df_gc)) * 100

entity               0.00000
code                 0.00000
year                 0.00000
ny_gdp_pcap_pp_kd    0.00000
owid_region          6.28453
dtype: float64

In [150]:
df_gc.duplicated().sum()

np.int64(0)

In [151]:
df_gc[df_gc.duplicated()]

Empty DataFrame
Columns: [entity, code, year, ny_gdp_pcap_pp_kd, owid_region]
Index: []

In [152]:
(df_gc['ny_gdp_pcap_pp_kd'] < 0).sum()

np.int64(0)

In [153]:
(df_gc['year'] > now.year).sum()

np.int64(0)

**Assessment:** There are some missing values in the column **owid_region**, **Columns** must be renamed and the groups, The **entity** columns has some grouped countries which needs to be removed

## Average Years of Schooling

In [154]:
df_sc.head()

,entity,code,year,literacy_rate,mf_youth_and_adults__15_64_years__average_years_of_education,population_historical,owid_region
0,Afghanistan,AFG,1870,NaN,0.01,4101170.0,Asia
1,Afghanistan,AFG,1875,NaN,0.01,4193635.0,Asia
2,Afghanistan,AFG,1880,NaN,0.01,4288021.0,Asia
3,Afghanistan,AFG,1885,NaN,0.01,4384343.0,Asia
4,Afghanistan,AFG,1890,NaN,0.01,4482635.0,Asia

In [155]:
df_sc.isnull().sum()

entity                                                             0
code                                                             890
year                                                               0
literacy_rate                                                   3365
mf_youth_and_adults__15_64_years__average_years_of_education    1697
population_historical                                            605
owid_region                                                      893
dtype: int64

In [156]:
len(df_gc)

7240

In [157]:
# Percent of missing values
(df_sc.isnull().sum() / len(df_sc)) * 100

entity                                                           0.000000
code                                                            16.589003
year                                                             0.000000
literacy_rate                                                   62.721342
mf_youth_and_adults__15_64_years__average_years_of_education    31.630941
population_historical                                           11.276794
owid_region                                                     16.644921
dtype: float64

In [158]:
df_sc.duplicated().sum()

np.int64(0)

In [159]:
df_sc[df_sc.duplicated()]

Empty DataFrame
Columns: [entity, code, year, literacy_rate, mf_youth_and_adults__15_64_years__average_years_of_education, population_historical, owid_region]
Index: []

In [160]:
(df_sc['mf_youth_and_adults__15_64_years__average_years_of_education'] > 15).sum()

np.int64(0)

In [161]:
col = 'literacy_rate'
print(((df_ip[col] < 0) | (df_ip[col] > 100)).sum())

0

In [162]:
(df_sc['year'] > now.year).sum()

np.int64(0)

**Assessment:** There are some missing values in all columns **except entity and year**, **Columns** must be renamed and the groups, The **entity** columns has some grouped countries which needs to be removed